### ISSUE TITLE
Miguel<>Shervin Us Agreement

### ISSUE THREAD

**Issue by shervine** [USfoundation/org-design#12]
Lets get this signed and started :)

Document draft:

https://docs.google.com/document/d/1uHC-EaCQ2U2W6hzeWf9jYlfX58xZRcotGLX_opEEIGU

Will sign and place in DocuSign.

**Comment by grumo** [comment]
Perfect. Let's sign it!

**Comment by shervine** [comment]
@grumo Done Done:

https://drive.google.com/file/d/0B4X48PHkwK8sdGROSll6Q0l2emc/view?usp=sharing
